version: "3.9"

services:
  grobid:
    image: lfoppiano/grobid:0.8.0
    ports:
      - "8070:8070"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - FRONTEND_URL=http://localhost:3000
      - GROBID_URL=http://grobid:8070
    depends_on:
      - grobid

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
